version: '3.8'

services:
  app:
    build: .
    ports:
      - "8889:8889"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/thejasdb2
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Dumpling@2501
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=thejasdb2
      - MYSQL_ROOT_PASSWORD=Dumpling@2501
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: